version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: products-mysql-app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysql
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data:

# version: "3"
# services:
#   nodejs:
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     image: products-api-app
#     ports:
#       - "3001:3000"
#     depends_on:
#       - mysql
#     container_name: products-api-app
#     environment:
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_DB: Products
#     restart: always
#   mysql:
#     build: ./mysql
#     command: --default-authentication-plugin=mysql_native_password
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: Products
#     container_name: products-mysql-app
#     ports:
#       - "3002:3306"
#     volumes:
#       - products-db:/var/lib/mysql
# volumes:
#   products-db: